### ISSUE TITLE
GenPipes-v3.3.0:  Quick review of latest pipeline steps in 3.3.0 branch to ensure RTD docs are in sync for 3.3.0 release

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#116]
HiC is updated via  #115. Review and match master branch other pipelines Readme to see if all steps are in sync with RTD docs.

**Comment by shaloo** [comment]
* Issues in chipseq pipeline #117 
* Issues in dnaseq pipeline mugqic option steps #118 
* Pipeline steps need updating in dnaseq_higcov #119 
* Methylseq pipeline steps need updating #120
* Nanopore pipeline shows up in https://bitbucket.org/mugqic/genpipes/src/3.3.0/pipelines/ branch so it needs to be enabled in docs #121

**Comment by shaloo** [comment]
Addressed as all open issues wrt v3.3.0 updates (afaik from src tree branch v3.3.0) have been addressed. RN will be added once @ehenrion shares the same.

**Comment by pphector** [comment]
Hello Shaloo. Apologies for the confusion, but in reality there are two nanopore pipelines that will be featured in genpipes. There is the current nanopore pipeline, which is already implemented and live and there is an upcoming nanopore pipeline that is specifically for COVID-19 (that will be called covseq_nanopore). 

The documentation you have in the master branch of read the docs right now is incorrect. It corresponds to what will become the covseq_nanopore pipeline. However, the current pipeline that is already there has documentation that is available and that should replace what you have already. To see it check this page: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/nanopore/

I don't know if this makes sense?

**Comment by shaloo** [comment]
It does. Thanks @pphector.
