### ISSUE TITLE
CovSeq update 3.6.0 release - RTD docs

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#131]
Hector mentioned that Covseq pipeline has also got updated(post 3.5.0 release scheduled early Aug) - that needs to be captured in RTD as well along with schema diagram

**Comment by ehenrion** [comment]
Hi Shaloo,
The CoVSeq update is actually not part of the 3.5.0 release.
It is still being tested and should be included in another release.

**Comment by shaloo** [comment]
Updates via Paul S:

Hi Shaloo! We are doing a new release with a covseq update.
The main update is that freebayes is now used to do the variants calling (so 2 different tools ivar and freebayes doing the same to have 2 consensus files) and also the report is generated as a new step with ncovtools (this report is done separately on ivar variants and on freebayes variants).

To do:

*  Readme.md update at mugqic/bitbucket repo for freebayes change
*  Workflow update?  (Mermaid diagram + manual one until mermaid is reviewed and accepted via PR for all pipelines post 3.5.0 release)
*  RTD docs pipeline reference guide update accordingly

Reference: https://bitbucket.org/mugqic/genpipes/commits/a1f3040b597df7e90cba1ee9d9dbb8f3c99784ac

**Comment by shaloo** [comment]
Done via #141
