### ISSUE TITLE
#DocUpdate: Need information sources for updating GetStarted Guide section on viewing and analysing results

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#14]
In the GenPipes RTD Getting Started Guide the following section needs to be populated with relevant information for new users.

https://genpipes.readthedocs.io/en/latest/get-started/gp_job_results.html

In the previous section on running genpipes, we have provided commands on running Hi-C pipeline on Compute Canada GenPipes deployment.  What happens next? How does a user view the results? Are these pipeline specific? Tool specific?  We need to provide some guidance to new users on these aspects in this section of the guide.

**Comment by shaloo** [comment]
References:

* Logs - first time GenPipes deployment / CC access data that I saved in May19
* GenPipes Google forum for e.g. https://groups.google.com/forum/#!topic/GenPipes/w276Sl5Lfek
and others such as:

- https://groups.google.com/forum/#!topic/GenPipes/V2rbTJriTiM (French)
- issues with new genome installation - how to use scripts - check with Hector if there is something relevant in this thread https://groups.google.com/forum/#!topic/GenPipes/l9bMG-nCCvM
- issues with local deployment (non container?) - this may be a dead thread but check if there is anything relevant that can be added in troubleshooting guide for new genpipes users https://groups.google.com/forum/#!topic/GenPipes/R_tFoC12U-M 
- out of memory issues https://groups.google.com/forum/#!topic/GenPipes/7QskD_lL5I0
- RNA seq pipeline issue (faced by more than 1 user) that required STAR parameter fix and buffer sizing see https://groups.google.com/forum/#!topic/GenPipes/EC2VeLz3i0Y

**Comment by rdali** [comment]
I currently do not have time to draft this; I might be able to in another few weeks. @pphector, Edouard and Mathieu might be able to help.

**Comment by shaloo** [comment]
Duplicate of #59. Closing this as this issue is being addressed via #59.
