### ISSUE TITLE
Tip about cluster specific .inis shows up twice in all pipeline docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#206]
In all of the pipelines reference guides (https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipeline_ref.html), the tip about using cluster-specific .ini files for each of the compute canada clusters shows up twice, once before the warning about using the -g option and once after the warning. 

An example from amplicon seq: https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipelines/gp_ampliconseq.html#example-run

**Comment by shaloo** [comment]
Thanks @MareikeJaniak. Fixed.
