### ISSUE TITLE
Outdated compute canada access command?

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#207]
I think the command for accessing compute canada in the docs might be outdated. The command shown is `ssh myaccount@mp2b.ccs.usherbrooke.ca` but I think it should be `ssh myaccount@beluga.computecanada.ca` (for beluga, for others replace with the desired cluster name).

Link to issue:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/deploy/access_gp_pre_installed.html#step-2-connect-to-compute-canada-servers

**Comment by shaloo** [comment]
@MareikeJaniak Thx for the update!

**Comment by MareikeJaniak** [comment]
Thanks for updating this command, Shaloo! Someone just pointed out that the example for Windows users is still outdated:
https://genpipes.readthedocs.io/en/latest/deploy/access_gp_pre_installed.html#step-2-connect-to-compute-canada-servers

Under Windows (Putty), `mp2b.ccs.usherbrooke.ca` should say `beluga.computecanada.ca`
