### ISSUE TITLE
log_report script usage only described for pbs, not slurm

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#208]
In the docs describing the usage of the log_report script, only the usage of log_report.pl is described, not the log_report.py version:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/get-started/gp_job_results.html?highlight=log_report.pl#genpipes-results

log_report.pl is used for generating the log report on abacus, while log_report.py is used on the compute canada clusters. Full command:
`$MUGQIC_PIPELINES_HOME/utils/log_report.py job_output/{TECHNOLOGY}_job_list_{DATE}T{TIME} --tsv log.out` (--tsv will provide the detailed output that's automatically generated by the .pl version)

**Comment by shaloo** [comment]
@MareikeJaniak Let me know if the fix looks okay.

**Comment by MareikeJaniak** [comment]
Looks great! Thanks, Shaloo!
