### ISSUE TITLE
Links to test data in tutorial do not work

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#209]
This is a known issues, just documenting it here again. 

The links for the hicseq and chipseq test datasets provided in the tutorial do not work:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/tutorials/genpipes_tutorial.html#hicseq-test-dataset
and 
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/tutorials/genpipes_tutorial.html#chipseq-test-dataset

Hector has looked for the missing files but hasn't been able to find them. Instead of linking to these datasets, we could change the descriptions of the test datasets and link instead to the other test datasets available for these two pipelines on the testdata page:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/resources/testdataset.html

**Comment by MareikeJaniak** [comment]
Related to this issue, the link in the example run under 'getting started' also doesn't work and could be replaced with the data from the testdata page:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/get-started/using_gp.html#example-run

**Comment by shaloo** [comment]
Done, thx @MareikeJaniak Also fixed other similar links.
