### ISSUE TITLE
Reference to old server in docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#210]
There are several references to the guillimin server in the docs. As far as I know, this server isn't used anymore (correct me if I'm wrong!) and has been replaced (?) by abacus. 

The references to guillimin in the following places can be replaced with abacus:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/tutorials/genpipes_tutorial.html?highlight=guillimin#running-genpipes-on-compute-canada-servers
and 
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/tutorials/genpipes_tutorial.html?highlight=guillimin#hicseq-test-dataset
and
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/get-started/using_gp.html?highlight=guillimin#example-run

**Comment by shaloo** [comment]
Replacing Guillimin references with Abacus as suggested across ALL docs (other than dated release notes when Guillimin was there) besides the ones listed above. Thx @MareikeJaniak
