### ISSUE TITLE
covseq test dataset not available

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#211]
The link to the covseq test dataset here does not work:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/resources/testdataset.html

**Comment by shaloo** [comment]
@pphector mentioned that the covseq pipeline test dataset sharing may have privacy issues.  I'd just put a placeholder (non existent) filename.  

Is there some publicly shareable covseq test data set available somewhere that I can link instead? Pls lmk.
@MareikeJaniak

**Comment by shaloo** [comment]
For now, I am removing the non-existent file and adding a note like this:
<img width="642" alt="Screenshot 2023-04-23 at 2 15 49 PM" src="https://user-images.githubusercontent.com/5890484/233829555-37d6432a-ad26-42e5-b9c8-b63c83bedb8b.png">

**Comment by MareikeJaniak** [comment]
Hi @shaloo, 
I'm not sure if there's a sharable dataset, but the note you added looks like a good solution in the meantime. It avoids potential confusion or questions about the dataset being missing. 

Maybe @pphector can weigh in on whether there is a sharable dataset for covseq?

**Comment by pphector** [comment]
Hmm... I think there is possibly a dataset that we could share for covseq. To certify the lab we have a set of non-clinical samples we have sequenced a few times. I think a panel of 2-4 of those viral genomes would be a good dataset. I need some time to prepare it though.

**Comment by shaloo** [comment]
@pphector can u pls share the CoVSeq testdataset mentioned above? Is it ready? Lmk if there is anything I can do to help speed it up and close this issue. Thx.

cc: @MareikeJaniak

**Comment by shaloo** [comment]
@pphector should I close this issue or do you plan to share covseq test dataset?

**Comment by pphector** [comment]
I think we can remove the link and not share the covseq dataset. That way we can close this ticket. I haven't had time to find a suitable dataset to share and this pipeline is no longer as widely used as before.

**Comment by shaloo** [comment]
See highlighted updates:
<img width="1119" alt="Screenshot 2024-05-14 at 5 02 25 PM" src="https://github.com/c3g/GenPipes/assets/5890484/35f2b06e-42c2-4348-a49d-8e306d515ee4">Docs published at RTD
