### ISSUE TITLE
Minor link issues on testdata page in docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#212]
There are a few small issues with links on the testdata page:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/resources/testdataset.html#genpipes-test-datasets

- In first column of the table listing the test datasets for each pipeline, the link for the tumor pair pipeline actually points to the page for dnaseq, instead of tumor pair. 
- At the bottom of the page, under bioinformatics resources (https://genpipes.readthedocs.io/en/genpipes-v4.4.1/resources/testdataset.html#bioinformatic-resources), the 'Bioinformatics resources' link is dead
- In the same section, the last link to the latest test datasets labelled 'download page' also does not work

**Comment by shaloo** [comment]
@MareikeJaniak The TumorPair test dataset link in the docs is this.  https://datahub-90-cw3.p.genap.ca/tumorPair.chr19.tar.gz. Is this incorrect?  Maybe the file name is different.  Can Rob Eveleigh help?  I don't have his GitHub handle to tag him.

**Comment by shaloo** [comment]
The rest of the links you mentioned, I have fixed by looking up the c3g website and changing them to:

https://computationalgenomics.ca/cvmfs-genome/. (Bioinformatics Genome listing)
and 
https://datahub-90-cw3.p.genap.ca. (download page)

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
Sorry, I didn't mean the link to the tumor pair test dataset, but the link to the tumor pair pipeline documentation (left column in the table). The link to the dataset is fine, but clicking on "TumorPair Seq" leads to the documentation for dnaseq, instead of the docs for tumor pair.
