### ISSUE TITLE
Details for methylseq pipeline protocols (-t flag)

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#214]
In the docs for methylseq pipeline usage, the -t flag isn't described in detail:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipelines/gp_wgs_methylseq.html#usage

This pipeline technically has three difference protocols (-t bismark, dragen, and hybrid) as shown in the brief overview, but the -t flag isn't further explained under the optional arguments, which could cause confusion. For most users, only the bismark protocol (default) is applicable, since the dragen and hybrid protocols require the use of the proprietary dragen platform, which is not available on compute canada clusters and requires an active license on the abacus cluster. This should be explained under "optional arguments" to avoid confusion.

**Comment by shaloo** [comment]
@MareikeJaniak That's great input. Sure, will do that.

**Comment by shaloo** [comment]
@MareikeJaniak - Is it this dragon platform that you referred to?  Planning to add a link in the text hence checking...
https://sapac.illumina.com/products/by-type/informatics-products/dragen-bio-it-platform.html

**Comment by MareikeJaniak** [comment]
Thanks, Shaloo! Yes, it's the Illumina dragen platform. The warning you added looks great to me!
