### ISSUE TITLE
Example command for nanopore pipeline is incomplete in docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#215]
The example command for the nanopore pipeline in the docs is incomplete:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipelines/gp_nanopore.html#example-run

**Comment by shaloo** [comment]
@MareikeJaniak I checked[ the latest Readme File for Nanopore](https://bitbucket.org/mugqic/genpipes/src/master/pipelines/nanopore/README.md), it does not list an example command.  Can you share one pls for the docs?

**Comment by MareikeJaniak** [comment]
You're right, I don't know why this is missing for nanopore. I will look into it. In the meantime, this is what the command should look like:
`nanopore.py -c nanopore.base.ini beluga.ini -r /cvmfs/soft.mugqic/root/testdata/nanopore/readset.nanopore.txt -o nanopore -g nanopore_commands.sh`
