### ISSUE TITLE
More detailed description of -t flag in tumor pair pipeline docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#216]
The description of the -t flag for the tumor pair pipeline in the docs could be more detailed: 
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipelines/gp_tumourpair.html#usage

No default is provided in the description, for example, and a brief description of what the different protocols are might be useful here. (Ensemble is the default.) This might not just be an issue for the docs, but for the command help message in general.

**Comment by shaloo** [comment]
This is fixed for Tumor Pair in the latest release https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_tumourpair.html

Also reviewing and fixing for all other pipelines.
