### ISSUE TITLE
Error in example Chipseq readset file

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#219]
Hi Shaloo, 

There is a small error in the example for the chipseq readset file here: https://genpipes.readthedocs.io/en/genpipes-v4.4.1/get-started/concepts/readset_file.html#example-of-chip-seq-readset-file

Right now there are the following entries for the first four columns (Sample-Readset-MarkName-MarkType):
sampleA-readset1-H3K27ac-N
sampleA-readset2-H3K27ac-I
sampleB-readset3-Input-N
sampleB-readset4-Input-I

But should it be:
sampleA-readset1-H3K27ac-N
sampleA-readset2-Input-I
sampleB-readset3-H3K27ac-N
sampleB-readset4-Input-I

I hope this makes sense! Let me know if it's not clear! Thanks!

**Comment by shaloo** [comment]
@MareikeJaniak Is this fix okay: https://genpipes.readthedocs.io/en/master/get-started/concepts/readset_file.html#example-of-chip-seq-readset-file

**Comment by MareikeJaniak** [comment]
Yes, that's great, thank you!
