### ISSUE TITLE
#DocUpdates: Need more info to complete GenPipes deployment guide for GCP

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#22]
Please refer to https://genpipes.readthedocs.io/en/latest/deploy/dep_gp_cloud_gcp.html RTD document.  We need to add instructions similar to what we have created for deploying GenPipes in a container.  The level of detail in https://bitbucket.org/mugqic/cloud_deplyoment/src/master/README.md file is missing.

Assigning to Rola to figure out who can help in filling in this information for GenPipes in the cloud.  Hector / Pierre / someone else.

Suggestion: I can pitch in and try it out myself using information for GenPipes deployment (local server) and container and what I know about accessing GenPipes in CC servers.  However, I do not have a GCP account so I cannot try it out myself at the moment.  If a temp account is available say for a week for GenPipes usage, I can try it out myself and generate these instructions. Alternately, can someone from GenPipes who knows them already, a *working set of instructions* , please provide the details in README.md file for GenPipes in the cloud?

Thanks in advance.

**Comment by rdali** [comment]
The best person to contact for all GCP and container issues is Pierre-Olivier. He is the person who set it up and is using it. You can catch him on slack or by email (let me know if you have any issues getting a hold of him).

It would be a great idea if you can test it yourself using a GCP account; you would have a different view than PO. We tend to test with free Google credit which seems fairly easy to get, if you can't get any, I can check with Pierre-Olivier to see if we can add you to our account.

**Comment by shaloo** [comment]
Hi Pierre, Rola pointed me in your direction - hence this note.
I'm trying to add information in 'Read The Docs' GenPipes documentation (see https://genpipes.readthedocs.io/en/latest/ )
corresponding to deploying and using GenPipes in the cloud (see section here: https://genpipes.readthedocs.io/en/latest/deploy/dep_gp_cloud_gcp.html).  

In this context, I first found the repository - https://bitbucket.org/mugqic/cloud_deplyoment/src/master/ and that didn't seem like a stable/working/correct location as it has no README content that I can utilise.  Today, I noticed another repository - https://bitbucket.org/mugqic/cloud_deplyoment/src/master/gcp/ and that appears to be the right one but I would like to confirm hence this query:

1.  Are the following pieces of information complete and sufficient for 'how to deploy and use GenPipes in GCP'?

A. http://www.computationalgenomics.ca/genpipes-in-the-cloud/  page
B. https://bitbucket.org/mugqic/cloud_deplyoment/src/master/gcp/README.md file

2. Is there a temporary GCP account that I can borrow in order to test/validate these instructions and then put them in RTD docs for GenPipes? Unfortunately, I cannot use my work/personal account for this work item but would really like to do a test run of the instructions as I put them in the user guides.

Looking forward to your inputs!
