### ISSUE TITLE
Broken links on accessing genpipes on CC servers page

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#220]
Someone pointed out the following broken links on this page:
https://genpipes.readthedocs.io/en/latest/deploy/access_gp_pre_installed.html#step-2-connect-to-compute-canada-servers

Within the Note under Step 2, the links to "Bioinformatics Resources" and "available genomes" are broken. For genomes, the issue is just a typo, the correct link should be: `https://computationalgenomics.ca/cvmfs-genome/`

The genome link appears again at the bottom of the page, so also needs to be corrected here: "For a complete list of all available reference genomes, visit [genome page](https://www.computationalgenomics.ca/cvmfs-genome/)." 

The links to "module page" further down the page are also broken. I don't know what the correct link for "module page" and "Bioinformatics Resources" should be, the page does not seem to be complete on the computationalgenomics.ca site. @pphector, do you know who to ask about this?

**Comment by shaloo** [comment]
@MareikeJaniak @pphector I have figured out the required links and updated accordingly. Please see:

https://computationalgenomics.ca/cvmfs-genome/
https://docs.alliancecan.ca/wiki/Available_software>

**Comment by pphector** [comment]
For the modules, we can use the following link: https://computationalgenomics.ca/cvmfs-2/
