### ISSUE TITLE
Typo on pre-req checklist page

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#221]
A user found this typo on the pre-req checklist page:
https://genpipes.readthedocs.io/en/latest/get-started/pre_req_chklist.html#docs-pre-req-chklist

"Ensure CVMFS is mounted (??? Is this valid for non container too?)"

@ehenrion, can you provide more details on when this is necessary and how to ensure this?

**Comment by shaloo** [comment]
For now, I am simply fixing the typo. If Ed responds later with more inputs on whether non-container deployments too need to ensure this, I can add that information then.
