### ISSUE TITLE
Broken links on workshop page

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#223]
The links on the workshops page are broken:
https://genpipes.readthedocs.io/en/latest/resources/workshops.html

@pphector Are these slides and resources hosted elsewhere?

**Comment by pphector** [comment]
I created a new location for the data, we can replace this link for this newer location: 
https://drive.google.com/drive/folders/1B1NKPmA_37xJsGILHXcdIM206hWCPlH8?usp=sharing
