### ISSUE TITLE
RNAseq documentation needs updating

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#224]
The documentation for the RNAseq pipeline is a bit outdated:
https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_rnaseq.html

Opening this issue as a note to myself and the TD team to update this :) 
@ehenrion @pphector

**Comment by shaloo** [comment]
https://genpipes.readthedocs.io/en/genpipes-v4.6.0/user_guide/pipelines/gp_rnaseq.html
