### ISSUE TITLE
Design file example confusing

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#227]
Hi!

I was helping a student with a chipseq issue today and I realized that there is something confusing in the documentation. On the genpipes tutorial page, the section about creating a design file (https://genpipes.readthedocs.io/en/latest/tutorials/genpipes_tutorial.html#creating-a-design-file) uses a chipseq design file as an example, even though chipseq design files are different from the other design files. I also think it's using an outdated chipseq design file format. (It's correct on the actual chipseq pipeline page: https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_chipseq.html).

Correct me if I'm wrong, but maybe it would be better to replace this example (https://genpipes.readthedocs.io/en/latest/tutorials/genpipes_tutorial.html#creating-a-design-file and the following section) with an rnaseq example or something similar that's more representative of a standard design file? @pphector, what do you think?

**Comment by shaloo** [comment]
@MareikeJaniak thank you for pointing this out! 👍 

I have updated chips.  Will discuss with @pphector this Tuesday and if he recommends, will open a new GitHub issue and update the tutorial example to RNASeq.  Can u pls share some design file / example content with me?  We can set up a call this week if appropriate and I can gather all inputs from you to update the present chipseq design tutorial section to RNAseq one. okay?

**Comment by MareikeJaniak** [comment]
Attaching the example design file for rnaseq here. I think we can just use the example data for rnaseq, right? Happy to have a call to help. 
[design.rnaseq.txt](https://github.com/c3g/GenPipes/files/12221414/design.rnaseq.txt)

**Comment by MareikeJaniak** [comment]
Looks like I already sent this! Let me know if this is enough to put together the example and replace the current chipseq example. If not, I can try to write up a draft of something.

**Comment by shaloo** [comment]
@MareikeJaniak @pphector 
Regarding the design file shared above for chipseq tutorial example here:   https://genpipes.readthedocs.io/en/shaloo-gp-5.0-layout/tutorials/genpipes_tutorial.html#chipseq-test-dataset

Is it the same for both protocols? chipseq and atacseq? Lmk and I will update it for 5.0 docs. I'm assuming we need to update 4.6.1 docs as well or not?

**Comment by MareikeJaniak** [comment]
The current description looks correct to me.

**Comment by shaloo** [comment]
Closing it. Thx.

**Comment by shaloo** [comment]
JFYI Updates for 4.6.1 are done [here](https://genpipes.readthedocs.io/en/latest/) but not published through the RTD version flyer (dropdown)as discussed in July / last call.

**Comment by jamesaliba** [comment]
Hello,

Im still confused, is 1 input and 2 its IP, or is 1 control and 2 a treatment (each possessing their own inputs). And if thats the case should we also add 1 and 2 respectively to the inputs along with the samples? Im trying to find: ControlvsTreatment and sampleIPvs samples input, in this case the sample name is control 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JAMES~1.SAL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JAMES~1.SAL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sample | MarkName | ControlvsTreatment | ControlvsTreatment | TargetIPvsInput_control | TargetIPvsInput_control
-- | -- | -- | -- | -- | --
Control | Input | 1 | 0 | 1 | 1
Control | TargetIP | 1 | 1 | 2 | 1
Treatment | Input | 2 | 0 | 0 | 0
Treatment | TargetIP | 2 | 2 | 0 | 0



</body>

</html>

**Comment by MareikeJaniak** [comment]
Hi James, 

The design file should not include the inputs. The design file is used for running the differential expression analysis, so it should only include the contrast between control and treatment. So in your example, only rows 2 and 4 should be included. 

Please see the relevant documentation here: 
https://genpipes.readthedocs.io/en/genpipes-v5.1.0/user_guide/pipelines/gp_chipseq.html under the tab Chip Sequencing Design File Format.

Best, 
Mareike
