### ISSUE TITLE
RNASeq steps are out of sync in release 4.4.2 needs updates and addition of 3 -t options plus diagram update

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#228]
1. bam_hard_clip no longer there
2. 3 -t options (cufflinks, string tie -> string tie(def), variants, cancer)
3. Diagram update

**Comment by MareikeJaniak** [comment]
I'm attaching the debug logs for the three rnaseq protocols here: stringtie, variants, and cancer. Let me know if you need anything else!

[GenPipes_rnaseq_cancer_debug.log](https://github.com/c3g/GenPipes/files/12381284/GenPipes_rnaseq_cancer_debug.log)
[GenPipes_rnaseq_stringtie_debug.log](https://github.com/c3g/GenPipes/files/12381285/GenPipes_rnaseq_stringtie_debug.log)
[GenPipes_rnaseq_variants_debug.log](https://github.com/c3g/GenPipes/files/12381286/GenPipes_rnaseq_variants_debug.log)

**Comment by shaloo** [comment]
Working on this after #224 fixes.
