### ISSUE TITLE
Update Methylseq for release 4.4.2

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#229]
Doc content update at RTD after reviewing latest steps. It may or may not require diagram update TBD.

**Comment by MareikeJaniak** [comment]
The debug log for the methylseq_bismark protocol is attached. The hybrid and dragen protocols also still exist, but they can only be used on abacus, so they are less relevant for most users. But let me know if you would like the debug logs for them as well. 

[GenPipes_methylseq_bismark_debug.log](https://github.com/c3g/GenPipes/files/12381218/GenPipes_methylseq_bismark_debug.log)
