### ISSUE TITLE
Chipseq update for release 4.4.2

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#230]
* Review changes required in pipeline user guide for 4.4.2 updates
* Sync up steps, diagram

**Comment by MareikeJaniak** [comment]
Hi Shaloo, I'm attaching the chipseq debug log reports for the chipseq and atacseq protocols, in case that helps! Let me know if you need anything else!

[GenPipes_chipseq_atacseq_debug.log](https://github.com/c3g/GenPipes/files/12381188/GenPipes_chipseq_atacseq_debug.log)
[GenPipes_chipseq_chipseq_debug.log](https://github.com/c3g/GenPipes/files/12381189/GenPipes_chipseq_chipseq_debug.log)
