### ISSUE TITLE
Detect dead links 

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#234]
Use deadlinkchecker tool to detect any dead links across latest 4.4.2 RTD GenPipes docs and create issues to fix them.

cc: @MareikeJaniak @pphector

**Comment by shaloo** [comment]
Dead link checks

<img width="1173" alt="Screenshot 2023-08-08 at 4 00 06 PM" src="https://github.com/c3g/GenPipes/assets/5890484/f1051554-0cf6-41c6-b040-c0b70f0ed1c1">

**Comment by MareikeJaniak** [comment]
I did a few spot checks and the NCBI and Nature links seem fine, I wonder if that was just an issue with too many requests in a short time period. I know ncbi is pretty strict about those. But the others will need investigation.

**Comment by shaloo** [comment]
Running it for v5.0 code and fixing compute Canada links -> Digital Research Alliance links
