### ISSUE TITLE
Update DiffBind on compute canada

### ISSUE THREAD

**Issue by ericloud** [c3g/GenPipes_Docs#237]
Hi Genpipe team, 

I have an issue with DiffBind, which seems to be fix in a new version `DiffBind_3.4.8`, see:
 - https://support.bioconductor.org/p/9141904/

The last version available on compute canada cluster is `DiffBind_3.0.15`, in the module `R_Bioconductor-4.0.3_3.12`. 
New version of `R_Bioconductor` don't seems to have DiffBind installed.

Could you install an updated version of DiffBind on `mugqic/R_Bioconductor` module, which work with chipseq pipeline ?

Thanks for your help,
Eric.

**Comment by ericloud** [comment]
I confirm that execute genpipes with last version of DiffBind, fix the issue.
I have install the last version of DiffBind on R/4.3.1 on a local cluster and the script `$R_TOOLS/DiffBind.R` of GenPipes works perfectly fine now.
On calcul canada I have the same issue explain in my previous message.

Best,
Eric.

**Comment by MareikeJaniak** [comment]
Hi Eric, 
Again, apologies for the delayed response! I believe that this issue has been addressed, the latest version of the mugqic/R_Bioconductor module is 4.2.2_3.16 which includes DiffBind 3.8.4. 
For a speedier response, it's best to open a ticket on our HelpDesk: https://genpipes.readthedocs.io/en/genpipes-v4.4.2/support/how_to_get_support.html
Best, 
Mareike
