### ISSUE TITLE
Using GEMINI with hg38

### ISSUE THREAD

**Issue by AidanGCr** [c3g/GenPipes_Docs#238]
Is it possible to update the pipeline to use GEMINI loader vcf2db by the quinlan-lab for hg38? I would be interested in testing this/working on a PR if the team is interested. 

Thanks,
Aidan

**Comment by MareikeJaniak** [comment]
Hi Aidan, 
Thanks for reaching out! Apologies for the delay in responding, this repo is used only for the documentation, so we don't monitor it as closely. The repository for GenPipes development is here: https://bitbucket.org/mugqic/genpipes/src/master/
You can also send an email to our help desk to get a faster response: pipelines@computationalgenomics.ca

Gemini/updates to gemini are definitely on our radar. We're exploring some alternatives at the moment, so I'm not sure if gemini will continue to be a part of the pipeline in future releases. Which pipeline are you referring to specifically? We currently use gemini in the dnaseq, tumor_pair, and rnaseq pipelines. However, the dnaseq and tumor_pair pipelines are getting a bit of overhaul, which may no longer include gemini. 

Best, 
Mareike

**Comment by AidanGCr** [comment]
Hi, 

No worries about the time to reply, my bad on commenting on the wrong repo! 

I was talking about the DNAseq pipeline specifically, as this is what I'm familiar with from my research work. Interesting to hear it's getting an overhaul, and potentially losing Gemini! I tend to agree that might be the best course of action. 

Well I guess then my help is not necessary! Thanks for the reply. 

Thanks, 
Aidan

**Comment by MareikeJaniak** [comment]
Hi Aidan, 

Yes, for dnaseq specifically I'd suggest waiting a bit, one of our team members is currently making changes to the pipeline. 

We do appreciate you reaching out and offering to work on it! Please don't hesitate to reach out with future requests or suggestions. You can also keep an eye on the google group for any future releases: https://groups.google.com/g/genpipes?pli=1

Best, 
Mareike
