### ISSUE TITLE
Nanopore pipeline documentation

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#244]
We just had a help desk ticket about the nanopore pipeline that ended up being about an issue in the readset format. This made me realize that the nanopore pipeline documentation could be improved: https://genpipes.readthedocs.io/en/genpipes-v4.4.5/user_guide/pipelines/gp_nanopore.html

We should provide details here about the format of the nanopore readset file, instead of just linking to it. 

@pphector @garantjm

**Comment by pphector** [comment]
Right :) I think we can definitely improve it. I might not have time to do it right away, but if you have some time I would appreciate the help. Otherwise, I will add it to the list of things to add to the docs in the near-mid future

**Comment by shaloo** [comment]
@MareikeJaniak @pphector I have tried to address this - see both Nanopore and Nanopore CovSeq pipeline example run section. here: https://genpipes.readthedocs.io/en/genpipes-v4.4.5/user_guide/pipelines/gp_nanopore.html#example-run and here https://genpipes.readthedocs.io/en/genpipes-v4.4.5/user_guide/pipelines/gp_nanopore_covseq.html#example-run
