### ISSUE TITLE
spike-in protocol (Chip Seq Diff Bind step with no input)

### ISSUE THREAD

**Issue by kkleinoros** [c3g/GenPipes_Docs#247]
any plans to add in a spike-in protocol to your pipeline?

**Comment by shaloo** [comment]
@MareikeJaniak @pphector do you have any inputs on this?

**Comment by shaloo** [comment]
We will update the doc to this effect:

Do not use ATAC sequence pipeline without any input. It requires input.  In future we plan to make it more robust and not run if input is not provided.

cc: @pphector @MareikeJaniak

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
The ATAC seq protocol can be used without input actually, the issue at the moment is the chipseq protocol expects an input at the DiffBind step. I am looking into this and it's possible that this will change for the next major release, but for now, if users want to run the chipseq protocol without an input, they should skip the DiffBind step and run it themselves locally.

**Comment by MareikeJaniak** [comment]
@kkleinoros Please send any questions related to the genpipes pipelines to our help desk, instead of posting them here. This repo is specifically for our documentation, not the genpipes code, so we don't monitor the issues here very closely.
