### ISSUE TITLE
GenPipes 5.0 scoping

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#250]
1. Blue color update in theme as used in GenPipes branding / other collaterals. (Update via @pphector the logo for genpipes uses the following blue RBG code: 11-45.9-73.7 or in HTML notation: 1c75bc). `Status: Done see branch https://github.com/c3g/GenPipes/tree/shaloo/gp-5.0-layout`
2. Add/update new user documentation as required. `TBD`
3. Add a note upfront and in relevant sections about CHR37 no longer supported in 5.0.0 those who still need to use it must refer to release 4.6.x.  `TBD`
4. Add a prominent note about deprecated pipelines (via @MareikeJaniak )
    - EpiQC pipeline `Done https://github.com/c3g/GenPipes/tree/shaloo/gp-5.0-layout`
    - HiC-Seq pipeline `Done https://github.com/c3g/GenPipes/tree/shaloo/gp-5.0-layout`
    - RNA-Seq cufflinks protocol (should already be deprecated):  `Yes it is! See  https://genpipes.readthedocs.io/en/genpipes-v4.6.1/user_guide/pipelines/gp_rnaseq.html`
    - AmpliconSeq qiime protocol `Done https://github.com/c3g/GenPipes/tree/shaloo/gp-5.0-layout`
    - The TumorPair and DNA-Seq High Coverage pipelines will be merged into the DNA-Seq pipeline as new protocols `TBD`

6. Others to be discussed in a meeting on June 18th(?) @pphector will set up one and I will join in to get the inputs from the team. ` TBD`
7. Investigate what all needs to be updated and can be cleaned up in docs for the major release in terms of content presentation. `TBD`

**Comment by shaloo** [comment]
Ref CHR38 https://cccg.slack.com/archives/C0KGMMSSC/p1714570898988199?thread_ts=1714569745.946189&cid=C0KGMMSSC

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
in regards to that thread, that is something I've actually just worked on yesterday. RNAseq will be updated to have GRCh38 as the default reference and DNASeq is already updated in dev. All other pipelines are already updated to default to 38.
