### ISSUE TITLE
Set up latest GenPipes modules for 5.0.0 and try a few pipelines

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#251]
This would help document the user guide section and incorporate changes from the older use model.

@MareikeJaniak @pphector can you help me set this up on Beluga/Cedar one of these days or show me a demo and I can take it from there.  It will also help me test/validate doc updates to ensure smooth onboarding for the new GenPipes users. Thx.

**Comment by MareikeJaniak** [comment]
Yes! Give us about a week to finalize the last big merge. Thanks for your help!

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
If you'd like to test out the new genpipes on beluga, you can clone the package branch from our bitbucket repo and pip install it like this:

```
# set up environment
export MUGQIC_INSTALL_HOME=/cvmfs/soft.mugqic/CentOS6
module use $MUGQIC_INSTALL_HOME/modulefiles

# clone and pip install
git clone --depth 3 --branch package https://bitbucket.org/mugqic/genpipes.git
export MUGQIC_PIPELINES_HOME=<clone_location>/genpipes
module purge
module load mugqic/python/3.11.1
pip install -e $MUGQIC_PIPELINES_HOME

# new genpipes command:
genpipes <pipeline> -c <base_ini> <server_ini> -t <protocol> -r <readset_file>

# Example:
genpipes dnaseq -c $MUGQIC_PIPELINES_HOME/genpipes/pipelines/dnaseq/dnaseq.base.ini \
  $MUGQIC_PIPELINES_HOME/genpipes/pipelines/common_ini/beluga.ini \
  -r $MUGQIC_INSTALL_HOME/testdata/dnaseq/readset.dnaseq.txt \
  -t germline_snv -g dnaseq_germline.commands.sh
```

**Comment by shaloo** [comment]
This works for me, thx.

I'm going to update (5.0 docs) all pipeline usage commands accordingly.

**Comment by shaloo** [comment]
Done.
