### ISSUE TITLE
RNASeq Denovo Trinity updates schema needs to be updated for 5.0 need debug logs

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#253]
@MareikeJaniak I noticed that there is just one step change here (rnammer to inferanal_transcriptome) - is it ok to just replace the same in schema? Or do I need to revisit the debug log in case the dependencies too have changed?
lmk. Thx.

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
Yes, for now the only change is the replacement of rnammer with infernal. However, I am going to add multiqc this week and remove some of the report steps. Will send the updated debug log when it's ready!
Best, 
Mareike

**Comment by MareikeJaniak** [comment]
Shaloo, did you still need a debug log for rnaseq_denovo_assembly trinity? I can't remember if I had sent one already.

**Comment by shaloo** [comment]
This is done, I validated. Thx @MareikeJaniak
