### ISSUE TITLE
Review chunking of pipeline commands in 5.0x

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#262]
In several places in using_gp and tutorials section we have listed the use of chunking command. Does that stay the same in 5.x or has it been deprecated?

Review and discuss with @MareikeJaniak @pphector then address in the docs accordingly.

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
I can confirm that the description of the chunk command on the docs is still correct for the new release. No changes needed!

**Comment by shaloo** [comment]
Closing as it is confirmed.
