### ISSUE TITLE
Small fix for ampliconseq docs

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#275]
Hi Shaloo, 

While you're updating the ampliconseq docs, I just noticed one small thing. 

In the options for ampliconseq, the `-t` flag is no longer available, since there is only one protocol now. So this should be removed from the docs for v5:

```
-t {dada2}, --type {dada2}

                          AmpliconSeq analysis type (default=dada2)
```
Thanks!

**Comment by shaloo** [comment]
This is addressed - see here: https://genpipes.readthedocs.io/en/genpipes-v5.0.1/user_guide/pipelines/gp_ampliconseq.html
