### ISSUE TITLE
#Admin: Add additional contributors to this Github Repository

### ISSUE THREAD

**Issue by pphector** [c3g/GenPipes_Docs#33]
Some key people from the team need to be added to this github so that they can take a look at the documentation and development (Edouard, Mathieu, etc.)...

**Comment by rdali** [comment]
I added Ed. I was surprised Mathieu is not even part of the github repo so I invited him and gave him full privileges. They should both have full access to read/write.

**Comment by shaloo** [comment]
Is this issue addressed now?  Can we close this or are we missing on any more contributors for GenPipes RTD documentation?
