### ISSUE TITLE
#DocUpdate: Add all recent workshop links in RTD documentation for GenPipes

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#35]
This ticket is based on Feedback received via Rola & Hector, Aug 16, 2019.

Ref: https://genpipes.readthedocs.io/en/latest/resources/workshops.html
Add all relevant GenPipes workshop content (slides, videos, docs, papers) in RTD.

Get in touch with Hector to grab a copy of the video that he mentioned during the call.

**Comment by shaloo** [comment]
@pphector :  Can you pls share the link to GenPipes tutorial / informative video that you referred to during Aug 16 Skype call?

**Comment by pphector** [comment]
I think that these were the videos that I was referring to: https://www.youtube.com/channel/UC2BHUTsZ3SEhmgtosnhhf8w/videos

They apply to the ampliconseq pipeline. In theory, we will be making more of these videos for other pipelines as well, but unfortunately we have not had time yet to produce similar videos for the rest of the pipelines. However, these two videos would be nice to have in RTD.

**Comment by shaloo** [comment]
Thanks, will add this in the appropriate sub-section at RTD.
