### ISSUE TITLE
#DocUpdate: RTD docs need to be published using GenPipes (admin) account on GitHub

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#40]
At present, we are publishing https://readthedocs.org/projects/genpipes/builds/9524031/ using shaloo's account on GitHub.  We need to use GenPipes (admin) or writer account on GitHub and create RTD project to publish the same.  Here is what is needed to be done:

1. Rola / GenPipes Admin creates a RTD account for GenPipes.  
2. We can link that account with pulling sources from C3g/GenPipes Github repository
3. Turn off Shaloo's GitHub account project that publishes on RTD currently as part of prototype / legacy.

**Comment by rdali** [comment]
I created an account on RTD. I will send you the credentials

**Comment by shaloo** [comment]
Received. Thx.  Will do the needful.

**Comment by shaloo** [comment]
Used c3g account at RTD and published the latest docs here:

https://genpipes-docs.readthedocs.io/index.html

Will give it a couple of days to stabilise and then delete the older https://genpipes.readthedocs.io/index.html which was published using my RTD credentials.  

Let me know what should be the slug for the documentation - should we keep it 'genpipes.readthedocs.org' (default) or 'genpipes-docs.readthedocs.org'?

**Comment by shaloo** [comment]
My vote is for default.  That way all the URL references in previous tickets, existing RTD content etc will still work and there is no change in URL.  After a week, I plan to delete the 'published' copy which is using my RTD account.

**Comment by shaloo** [comment]
Current status:

* Published GenPipes docs using C3G RTD account here:
* Previous versions are available (published using my GitHub/RTD accounts) here:

The latter will be removed (deleted) in a week's time.

**Comment by shaloo** [comment]
To make the switch, i had to delete the published copy using my account.  So here is the final status.

Latest GenPipes RTD docs (published using C3G RTD account) are now accessible on the same URL:

https://genpipes.readthedocs.io/en/latest/
