### ISSUE TITLE
#DocUpdate: Missing info in RNASeq Light Pipeline README.md file

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#41]
The following step description is missing from the RNA Sequencing Light pipeline:

kallisto_count_matrix

Secondly, for RTD docs, we need to put up example usage run command for ran sequence light pipeline?  Is there a tutorial/workshop that provides this data?  I saw RNASEq workshop but not sure if it is ok to use similar bam/other input test data as RNA Sequencing diff expression analysis workshop instructions for the 'light' pipeline as well. Please confirm or provide the correct command and links to test data that needs to be input.

Lastly, Is the RNA Seq Light pipeline under development?  If not, please remove the last line in README.md file that states so. https://bitbucket.org/mugqic/genpipes/src/master/pipelines/rnaseq_light/README.md

**Comment by shaloo** [comment]
part 1 and part 3 of this issue are pending.  These are dependencies that need to be resolved in order to close #37 and #38.

**Comment by pphector** [comment]
I just generated a pull request to the GenPipes dev branch so this issue is fixed for our next update. Once that happens, I will close the issue.

**Comment by shaloo** [comment]
Closing this issue and opening a separate one to address missing info in RNA Sequence Light pipeline.
