### ISSUE TITLE
#DocInput:  conpair_concordance_contamination missing info in tumor_pair readme.md

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#50]
The following user guide content at RTD is marked 'TBD' in the absence of available information. 

https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_tumourpair.html

Please provide the details of the step "conpair_concordance_contamination" mentioned in https://bitbucket.org/mugqic/genpipes/src/master/pipelines/tumor_pair/README.md source.

* Is it named ConPair or is it a typo - Compare?
* What does this step do? There are no details.

Actually several others are very cryptic - mostly program/code function names instead of what the step actually does/produces/solves.  Can someone spare a few minutes and talk about these to me - I can document them for RTD accordingly.  Thanks.

**Comment by pphector** [comment]
I will add Rob Eveleigh, who developed the pipeline to this thread. Maybe he can provide more insight.

**Comment by pphector** [comment]
I just assigned Rob (@robrollback )to this issue, he told me last week that when he has a bit of time he will take a look at your questions to answer them and hopefully expand on the tumour pair docs.

**Comment by robrollback** [comment]
Conpair (https://github.com/nygenome/Conpair) is a concordance and contamination estimator for tumor–normal pairs.  A quality control process to ensure the normal sample and cancer sample come from the same patient and to estimate the amount of normal sample is in the tumor and vice versa. 

If there is any other issues please let me know.

**Comment by shaloo** [comment]
Thanks @robrollback.
