### ISSUE TITLE
#DocSelfReview: Does GenPipes really require a Dev Guide?

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#61]
During GSoD prototype, the RTD docs TOC contained a section for GenPipes developers.  The objective was to help new GenPipes developers from the community to find their bearings wrt building, fixing, adding features to GenPipes. Assumption here was that GenPIpes is opensource.  

Are there any established GenPipes dev guidelines that can be added to RTD docs content?  If not, we can remove this section or just keep it as placeholder for now until we figure out where the information is and pull it into RTD. 

Please refer to the placeholder outline here:  https://genpipes.readthedocs.io/en/latest/development/dev_guide.html

**Comment by rdali** [comment]
The only thing I am aware of was this: https://bitbucket.org/mugqic/genpipes/src/master/README-GenAP_coding_standards.txt
but we would need more docs to establish a section for contributors. Maybe ask Mathieu if we can put resources here, otherwise just leave it as place holder for now?

**Comment by shaloo** [comment]
Thanks for the inputs, Rola.  For the time being, we can keep this very basic coding guideline set in one of the dev guide sections.
