### ISSUE TITLE
#DocSelfReview: Missing info in RNA Sequence Light Pipeline - is it under dev?

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#63]
The following step description is missing from the RNA Sequencing Light pipeline:

kallisto_count_matrix

Also, is the RNA Seq Light pipeline under development? If not, please remove the last line in README.md file that states so. https://bitbucket.org/mugqic/genpipes/src/master/pipelines/rnaseq_light/README.md

**Comment by pphector** [comment]
Created a pull request to address this issue, here: https://bitbucket.org/mugqic/genpipes/pull-requests/183

**Comment by shaloo** [comment]
This is addressed via recent updates for v3.4.0 hence closing
