### ISSUE TITLE
#DocReview Minor typos or non-urgent issues

### ISSUE THREAD

**Issue by pphector** [c3g/GenPipes_Docs#66]
This is a catch-all issue that will be used to report minor typos or non-urgent errors so that we can prioritize the work and avoid creating too many issues at once.

**Comment by dksenthil** [comment]
In  document [TumourPair](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_tumourpair.html )
The line `Cancer cells result from large structural alterations in their chromosomes that change the number of copies of affected genes on those chromosomes.` sounds like SV are the only reason for cancerous cells. It can be rephrased as `Cancer cells are majorly a result of large SV.....`

**Comment by dksenthil** [comment]
In document [HiC](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_hicseq.html).

The line praragraph `**Interaction Matrices Chr** In this step, IntraChromosomal interaction matrices are produced by Homer at resolutions defined in the ini config file and plotted by HiCPlotter. For details, see Homer Matrices. For details visit HiCPlotter Page.` has the section header in the same line .

Also  use the plural of `purpose` at  line `An example of the Hi-C report for an analysis on public data (GM12878 Rao. et al.) is available for illustration purpose only: Hi-C report.`

Line `Chicago will filter capture hic artifacts` does **hic** refer to .hic file or should have been HiC(change case)?

**Comment by shaloo** [comment]
Thank you @dksenthil for your inputs! :-)
Updates here https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_tumourpair.html and https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_hicseq.html

**Comment by pphector** [comment]
I will be adding all the other feedback we got from additional collaborators in the previous weeks. None are major, so I will just group them into this comment, if that's alright. Most of these involve adding information on our side, so I don't expect you to do all of them, I will just put them here so I can remember what we are missing and make sure that we add them. 

- In the [Citing and Citations page](https://genpipes.readthedocs.io/en/latest/resources/citation.html): 
    - The link to citation example number 2 does not work. 
- In the [Methylation Sequencing Pipeline page](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_wgs_methylseq.html): 
    - Add explanation on how to use the 'UMI BAM Tag Processing' (5) step, because it is unclear where the UMI information is coming from (if the user provides it or if it is built in). 
- In the [ChIP Seq pipeline page](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_chipseq.html): 
    - Step 12 'MACS2 call peak', specify that the '--nolambda' flag is activated and what it is doing. 
- In the [DNA seq pipeline page](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_dnaseq.html):
    - Mention that the pipeline now supports the choice of two trimmers: trimmomatic or skewer. 
    - Several steps have 'TBD' as their description. Fill out the missing information. 
- In the [ampliconseq page](https://genpipes.readthedocs.io/en/latest/user_guide/pipelines/gp_ampliconseq.html):
     - Add the flag '–t dada2' to the example command, since it is not obvious to regular users that the pipeline is using dada2 as a default. This would make it explicit and easier to understand. 
    - Several steps also have 'TBD'. 
- In the [Developer Guide](https://genpipes.readthedocs.io/en/latest/development/dev_guide.html#docs-dev-guide): 
    - For now, just link to the GenPipes Source code and specify that development should be done in a separate from which a pull request is sent. The pull request will be reviewed by someone from the GenPipes team before it is approved and merged into the 'dev' branch (I will work on the text with the help of Edouard).
    - Since this section will likely not be complete before the publication of the docs, we can just leave it with the simple points above and remove the question marks so that it does not look incomplete when we publish. 

That is all I have received for now. As mentioned, several of these points require some help from the people who developed each pipeline so that the step information can be added. I will try to contact the relevant people to have that information added. In our next meeting we can discuss if it is enough before we publish, but we should try to remove all the 'TBD' before we publish.

**Comment by shaloo** [comment]
The TBD in several steps in various pipelines require inputs from individual pipeline developers / maintainers.  The original readme file that lists these steps doesn't not contain any information regarding the same.  I am leaving those marked with label 'TBD-GenPipes-Dev' to ensure it is addressed in near future.  If README for the respective pipelines are updated, please ping me and I will be happy to pull in those changes for the RTD docs sources in c3g repository.

**Comment by shaloo** [comment]
Thank you for this feedback.  I have addressed all but the ones that GenPipes Pipeline developers need to fill in and provide information for various steps. That information is missing in original pipeline README.md as well.

**Comment by shaloo** [comment]
Addressed as suggested above. Hence closing.
