### ISSUE TITLE
#DocReview Feedback from Audrey Baguette

### ISSUE THREAD

**Issue by pphector** [c3g/GenPipes_Docs#67]
- In the “About” part, it is mentioned twice (main text and “Target Audience”) that the end-users are bioinformaticians, beginners or not. Could it be better to only mention “researchers/students needing bioinformatics tools” rather than “bioinformaticians”? I feel that even if the tutorials are clear and easy to follow, some might get scared by the labeling. If they do not see themselves as such, will they make the “effort” to look at the tutorials, or will they just give up the idea of trying GenPipes because they are not bioinformaticians? I think the emphasis should be more on the fact that GenPipes is so easy to use that anyone with basic knowledge of terminals could use it.

- “GenPipes: Step by Step >> Introducing GenPipes”: Typo under section What is GenPipes, “Capture Hi-Ca” should be “Capture Hi-C” if I’m not mistaken.

- In the step-by-step section, I am not sure it is 100% clear that while the readset and design files have to be created, the basic configuration files are installed with GenPipes and can be found on the Compute Canada servers, not that if supplementary configurations need to be specified, a new ini file can be created by the user and added to the -c parameter while running the command line. However, this couldn’t be cleared in the tutorial section, so I’m not sure it is mandatory in the step by step section.

- “GenPipes Tutorials >> GenPipes Tutorial” section “Running GenPipes on Cedar or Graham:” should maybe be renamed, since it actually makes a specification for Guillimin and not Cedar nor Graham which use default options.

**Comment by shaloo** [comment]
Thanks for the inputs Audrey Baguette and @pphector.  I will take care of these in next next couple of days.

**Comment by shaloo** [comment]
Updated - see https://genpipes.readthedocs.io/en/latest/, https://genpipes.readthedocs.io/en/latest/get-started/what_is_genpipes.html, https://genpipes.readthedocs.io/en/latest/get-started/what_is_genpipes.html#how-genpipes-works and https://genpipes.readthedocs.io/en/latest/tutorials/genpipes_tutorial.html#running-genpipes-on-compute-canada-servers
