### ISSUE TITLE
#Question Hi-C Real-Life Applications

### ISSUE THREAD

**Issue by pphector** [c3g/GenPipes_Docs#68]
This is a question sent to me from Audrey Baguette, a PhD student from Guillaume's lab. She wants to understand something mentioned in the "Real-Life Applications" section. 

> In the “Real-Life Applications” section, it is stated that the Hi-C pipeline’s further analyses may integrate ChIP-seq/RNA-seq data. Is this in the “bait intersect/capture intersect” steps?

**Comment by rdali** [comment]
yes, you can see which of your regions have ChIPSeq or RNASeq signal

**Comment by shaloo** [comment]
Adding relevant information content from this into GenPipes RTD documentation FAQ page.

**Comment by shaloo** [comment]
See updates here https://genpipes.readthedocs.io/en/latest/faq/faq_gp_dev.html#what-kind-of-further-analysis-be-done-using-hic-sequencing-pipeline

@pphector - can we close this issue now?

**Comment by shaloo** [comment]
Closing this - addressed via updates listed below:
 https://github.com/c3g/GenPipes/commit/cf5c508100fba1529c4cda7bf2b10217854bb326
