### ISSUE TITLE
Test Dataset links broken

### ISSUE THREAD

**Issue by rdali** [c3g/GenPipes_Docs#80]
The links to test dataset on the[ following page ](https://genpipes.readthedocs.io/en/latest/resources/testdataset.html) are broken.  The data was moved. 

The new links are at:
https://datahub-90-cw3.p.genap.ca/

instead of:
https://datahub-7826hyc9.udes.genap.ca/

**Comment by shaloo** [comment]
Thanks Rola,  I will update these right away.

**Comment by shaloo** [comment]
Done. Please refer to updated links here:  https://genpipes.readthedocs.io/en/latest/resources/testdataset.html

@rdali please close the issue if it works for you now after the fixes.

**Comment by rdali** [comment]
thanks!
