### ISSUE TITLE
Docs2.0: Guillimin server replacement info required

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#90]
The following file is reused to generate GenPipes 2.0 (draft) RTD content.  It refers to guillimin server which is apparently decommissioned.  Is there an alternate server/ini file that can be replaced in this source file?

https://datahub-90-cw3.p.genap.ca/testCommands.txt

cc: @rdali , @pphector

**Comment by ehenrion** [comment]
Hi Shaloo,
This needs to be confirmed but I would recommend using the 'beluga' .ini
files.
Thanks,
Edouard
---
Edouard Henrion
Software Developer
Canadian Centre for Computational Genomics (C3G) - Montréal node
Tel: (514) 398-3311, ext. 00721
http://computationalgenomics.ca

**Comment by rdali** [comment]
Done
