### ISSUE TITLE
Docs2.0:  auto-refresh test dataset usage commands file from bitbucket

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#92]
The following file is referred to by RTD docs (as-is).  At present, this file is outdated as it uses decommissioned server Guillimin.  We need to refresh it in RTD once this file is updated in bitbucket.  Keeping track of this task via this Github issue.

Ref:  https://datahub-90-cw3.p.genap.ca/testCommands.txt

Re-Used in RTD here:  https://genpipes.readthedocs.io/en/latest/tutorials/pipeline_usage_examples.html#doc-pipeline-usage-examples and in Makefile

**Comment by shaloo** [comment]
Received following inputs from Ed regarding usage of beluga but waiting on original file update (can I go ahead and issue a PR?):

>>
This needs to be confirmed but I would recommend using the 'beluga' .ini
files.
>>>

**Comment by rdali** [comment]
Done
